version: '3.8'

name: whatshare-server
services:
  db:
    container_name: database 
    image: prismagraphql/mongo-single-replica:5.0.3
    environment:
      MONGO_INITDB_ROOT_USERNAME: prisma
      MONGO_INITDB_ROOT_PASSWORD: prisma
    ports:
      - 27017:27017 
